# Generated by Django 5.0.4 on 2024-05-09 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_pedido_id_pago_pedido_estado_pago_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='id_producto',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='total',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='estado_pago',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='id_carrito',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='tipo_pago',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='total',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='accion',
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('enviado', 'Enviado'), ('recibido', 'Recibido'), ('cancelado', 'Cancelado'), ('no pagado', 'No pagado'), ('pagado', 'Pagado')], default='no pagado'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='CarritoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.carrito')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(choices=[('tarjeta', 'Tarjeta'), ('paypal', 'Paypal'), ('contrarreembolso', 'Contrarreembolso')], default='tarjeta')),
                ('num_tarjeta', models.CharField(max_length=16)),
                ('fecha_vencimiento', models.DateField()),
                ('cvc', models.CharField(max_length=3)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.pago'),
        ),
        migrations.CreateModel(
            name='PedidoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pedido')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
        ),
    ]
