# Generated by Django 5.0.4 on 2024-05-14 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_usuario_direccion_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateField(default=datetime.datetime(2024, 5, 14, 15, 18, 41, 738838, tzinfo=datetime.timezone.utc)),
        ),
    ]
