# Generated by Django 5.0.6 on 2024-05-28 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_producto_id_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritoproducto',
            name='total',
        ),
        migrations.RemoveField(
            model_name='pedidoproducto',
            name='total',
        ),
    ]
