# Generated by Django 5.0.6 on 2024-06-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_carritoproducto_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='images_producto/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, upload_to='images_producto/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen4',
            field=models.ImageField(blank=True, null=True, upload_to='images_producto/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen5',
            field=models.ImageField(blank=True, null=True, upload_to='images_producto/'),
        ),
    ]
