# Generated by Django 5.0.6 on 2024-06-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_producto_imagen2_producto_imagen3_producto_imagen4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
