# Generated by Django 5.0.4 on 2024-05-16 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_pedido_fecha_pedido'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateField(default=datetime.datetime(2024, 5, 16, 12, 54, 27, 446110, tzinfo=datetime.timezone.utc)),
        ),
    ]
