# Generated by Django 5.0.6 on 2024-05-20 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_usuario_managers_alter_pedido_fecha_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateField(default=datetime.datetime(2024, 5, 20, 8, 16, 49, 495304, tzinfo=datetime.timezone.utc)),
        ),
    ]
