# Generated by Django 5.0.6 on 2024-06-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_producto_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion_facturacion',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
