# Generated by Django 5.0.6 on 2024-06-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_pedido_direccion_pedido_direccion_facturacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='nombre_tarjeta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='cvc',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='num_tarjeta',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='tipo_pago',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta'), ('paypal', 'Paypal'), ('contrarreembolso', 'Contrarreembolso')], default='contrarreembolso'),
        ),
    ]
