# Generated by Django 5.0.6 on 2024-06-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_pago_nombre_tarjeta_alter_pago_cvc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='vendido',
            field=models.BooleanField(default=False),
        ),
    ]
